[package]
name = "edges"
# don't manually edit this version unless you're sure you want to circumvent the process documented in RELEASE.md
version = "0.3.2"
edition = "2021"
authors = ["@shnewto"]

description = "a library for getting the edges of objects in images with transparency"
readme = "README.md"
keywords = ["image", "edge", "transparency", "sprite", "bevy"]

homepage = "https://github.com/shnewto/edges"
repository = "https://github.com/shnewto/edges"

license = "MIT OR Apache-2.0"

[features]
default=[]
bevy=["dep:bevy"]

[dependencies]
glam = "0.25.0"
hashbrown = "0.14.5"
image = "0.24.9"
mashmap = "0.1.1"
ordered-float = "4.2.0"
thiserror = "1.0.57"

[dependencies.bevy]
version = "0.13.0"
default-features = false
features = ["bevy_render"]
optional = true

[dev-dependencies]
raqote = "0.8.4"
open = "5.1.2"

[[example]]
name = "bevy-image"

[[example]]
name = "dynamic-image"
